### ISSUE TITLE
Confirmed reports that there's npm install issue

### ISSUE THREAD

**Issue by Jeffchiucp** [jeff20009/WeatherReactApp#2]
Some User reported that there's npm install issue.
please confirm that is the case
WeatherReactApp-master npm install

npm ERR! Darwin 16.7.0

npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"

npm ERR! node v4.4.3

npm ERR! npm  v2.15.1

npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@0.14.9 does not satisfy its siblings' peerDependencies requirements!

npm ERR! peerinvalid Peer react-dom@0.14.9 wants react@^0.14.9

npm ERR! peerinvalid Peer react-google-maps@7.3.0 wants react@15.5.4

npm ERR! peerinvalid Peer react-redux@4.3.0 wants react@^0.14.0

npm ERR! peerinvalid Peer react-router@2.8.1 wants react@^0.14.0 || ^15.0.0

npm ERR! peerinvalid Peer react-sparklines@1.7.0 wants react@*

npm ERR! peerinvalid Peer react-addons-test-utils@0.14.8 wants react@^0.14.8

npm ERR! Please include the following file with any support request:

npm ERR!     /Users/jchiu/Downloads/WeatherReactApp-master/npm-debug.log

**Comment by jeff20009** [comment]
resolved the issue by uninstall and reinstall npm

**Comment by Jeffchiucp** [comment]
great. Thank you.
